### ISSUE TITLE
yum-repoforge no longer working

### ISSUE THREAD

**Issue by Gary-Armstrong** [dwradcliffe/chef-incron#10]
The maintainer of RPMforge/Repoforge has stopped it.  Specifically, the GPG key location is returning a 404.  I'd like to be able to spec a different repo (once I find one) via attribute.

**Comment by dwradcliffe** [comment]
I don't use yum anymore but I'm happy to accept a PR to fix this!

**Comment by Gary-Armstrong** [comment]
Turns out the yum-repoforge cookbook maintainer has fixed up things, so we can both ignore this now. :-)

**Comment by dwradcliffe** [comment]
Ok 😄
